### ISSUE TITLE
Resource should not be in TR space

### ISSUE THREAD

**Issue by yatil** [w3c/remote-meetings#28]
There is no good reason why this content should be in TR space, the W3C/WAI website has already [a related resource](https://www.w3.org/WAI/teach-advocate/accessible-presentations/) and the content of this document would be easier findable in the W3C/WAI navigation.

**Comment by jasonjgw** [comment]
This issue was negotiated with the Education and Outreach Working Group and considered by the Research Questions Task Force more than once during development of the document. It was decided to proceed with the Note-track publication, but made clear that Education and Outreach, Accessibility Guidelines Working Group or others were welcome to cite or make use of the material as they wished subsequently to its publication.

**Comment by yatil** [comment]
I would strongly ask the involved parties to reconsider. This format is harder to read, harder to find, harder to navigate, and harder to use. In addition the format leads many to believe this would be an official standard instead of – essentially – an article.

I’m not sure why one would deliberately make something less usable and hence less accessible than it needs to be.

**Comment by hidde** [comment]
Agreed, it is an excellent document, but the audience I can share this with is much smaller than it can be.

In this format it requires a lot of W3C-lingo knowledge from users/readers, which seems like an unnecessary barrier, this isn't a document that is only relevant to people in that category.
